# Generated by Django 5.2.17 on 2026-09-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='chat/audio/'),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
