# Generated by Django 5.1.15 on 2026-09-19 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('average_gestation_days', models.PositiveIntegerField(default=31)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Entrée / Vente'), ('expense', 'Dépense')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Rabbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag_number', models.CharField(help_text="Numéro de bague ou d'identification", max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1)),
                ('birth_date', models.DateField()),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('cage_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Reproducteur actif'), ('pregnant', 'En gestation'), ('lactating', 'En allaitement'), ('resting', 'En repos'), ('retired', 'Retiré / Réformé')], default='active', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rabbits/')),
                ('avatar_color_index', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rabbits', to='farm.breed')),
                ('dam', models.ForeignKey(blank=True, help_text='Mère (femelle)', limit_choices_to={'gender': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_offspring', to='farm.rabbit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rabbits', to=settings.AUTH_USER_MODEL)),
                ('sire', models.ForeignKey(blank=True, help_text='Père (mâle)', limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sire_offspring', to='farm.rabbit')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'tag_number')},
            },
        ),
        migrations.CreateModel(
            name='Mating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mating_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'En attente palpation'), ('confirmed', 'Gestante confirmée'), ('kindled', 'Mise bas réalisée'), ('failed', 'Infructueux')], default='pending', max_length=20)),
                ('palpation_date', models.DateField(blank=True, help_text='Date palpation (~J+12)', null=True)),
                ('nest_box_date', models.DateField(blank=True, help_text='Pose boîte à nid (~J+28)', null=True)),
                ('expected_kindling_date', models.DateField(blank=True, help_text='Date prévue mise bas (~J+31)', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matings', to=settings.AUTH_USER_MODEL)),
                ('female', models.ForeignKey(limit_choices_to={'gender': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='matings_as_dam', to='farm.rabbit')),
                ('male', models.ForeignKey(limit_choices_to={'gender': 'M'}, on_delete=django.db.models.deletion.CASCADE, related_name='matings_as_sire', to='farm.rabbit')),
            ],
            options={
                'ordering': ['-mating_date'],
            },
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('born_alive', models.PositiveIntegerField(default=0)),
                ('still_born', models.PositiveIntegerField(default=0)),
                ('weaned_count', models.PositiveIntegerField(blank=True, null=True)),
                ('weaning_date', models.DateField(blank=True, help_text='Date sevrage (~J+45)', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litters', to=settings.AUTH_USER_MODEL)),
                ('mating', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litter', to='farm.mating')),
                ('father', models.ForeignKey(blank=True, limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litters_as_father', to='farm.rabbit')),
                ('mother', models.ForeignKey(limit_choices_to={'gender': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='litters_as_mother', to='farm.rabbit')),
            ],
            options={
                'ordering': ['-birth_date'],
            },
        ),
        migrations.CreateModel(
            name='CareEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('vaccine', 'Vaccination'), ('deworming', 'Vermifuge'), ('antiparasitic', 'Anti-parasitaire'), ('coccidiosis', 'Coccidiose'), ('checkup', 'Contrôle général'), ('other', 'Autre soin')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('reminder_date', models.DateField(blank=True, help_text='Rappel prochain soin', null=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_events', to=settings.AUTH_USER_MODEL)),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_events', to='farm.rabbit')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
