# Generated by Django 5.1.15 on 2026-09-25 23:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_rabbitimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='compartment_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Numéro de la loge occupée dans la cage (1 = haut)', null=True),
        ),
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom ou code de la cage (ex. A1)', max_length=50)),
                ('location', models.CharField(blank=True, help_text='Emplacement (bâtiment, rangée...)', max_length=100, null=True)),
                ('compartments_count', models.PositiveSmallIntegerField(default=3, help_text='Nombre de loges de la cage', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='rabbit',
            name='cage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rabbits', to='farm.cage'),
        ),
        migrations.AddConstraint(
            model_name='rabbit',
            constraint=models.UniqueConstraint(condition=models.Q(('cage__isnull', False), ('compartment_number__isnull', False)), fields=('cage', 'compartment_number'), name='unique_rabbit_per_compartment'),
        ),
        migrations.AlterUniqueTogether(
            name='cage',
            unique_together={('owner', 'name')},
        ),
    ]
