# Generated by Django 5.2.17 on 2026-09-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_cage_grid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rabbit',
            name='unique_rabbit_per_compartment',
        ),
    ]
