# Generated by Django 5.2.17 on 2026-09-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_allow_several_rabbits_per_compartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='litter',
            name='died_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='litter',
            name='weaned_at',
            field=models.DateField(blank=True, help_text='Date du dernier sevrage effectué', null=True),
        ),
        migrations.AlterField(
            model_name='litter',
            name='weaning_date',
            field=models.DateField(blank=True, help_text='Date sevrage prévue (~J+45)', null=True),
        ),
    ]
