# Generated by Django 5.2.17 on 2026-09-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_litter_weaning_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='mating',
            name='palpation_done_at',
            field=models.DateField(blank=True, help_text='Date à laquelle la palpation a été effectuée', null=True),
        ),
        migrations.AlterField(
            model_name='mating',
            name='palpation_date',
            field=models.DateField(blank=True, help_text='Date palpation prévue (~J+12)', null=True),
        ),
    ]
