# Generated by Django 5.1.15 on 2026-09-26 16:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_mating_palpation_done'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('vaccine', 'Vaccin'), ('vitamin', 'Vitamine'), ('deworming', 'Déparasitant'), ('antiparasitic', 'Anti-parasitaire externe'), ('coccidiosis', 'Anti-coccidien'), ('antibiotic', 'Antibiotique'), ('other', 'Autre')], default='other', max_length=20)),
                ('renewal_days', models.PositiveIntegerField(blank=True, help_text='Durée en jours avant de renouveler le soin (vide = soin ponctuel)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_treatments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date à laquelle le soin a été effectué')),
                ('purpose', models.CharField(blank=True, default='', help_text='Motif du soin', max_length=200)),
                ('next_due_date', models.DateField(blank=True, help_text='Prochaine échéance de renouvellement', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_records', to=settings.AUTH_USER_MODEL)),
                ('rabbits', models.ManyToManyField(related_name='care_records', to='farm.rabbit')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='farm.caretreatment')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
