# Generated by Django 5.1.15 on 2026-10-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_cage_client_uuid_cage_deleted_at_cage_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='breeds/'),
        ),
    ]
