# Generated by Django 5.2.17 on 2026-09-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_otpverification_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('XOF', 'Franc CFA (BCEAO)'), ('XAF', 'Franc CFA (BEAC)'), ('USD', 'Dollar américain'), ('GBP', 'Livre sterling'), ('CHF', 'Franc suisse'), ('CAD', 'Dollar canadien'), ('MAD', 'Dirham marocain'), ('TND', 'Dinar tunisien'), ('DZD', 'Dinar algérien'), ('NGN', 'Naira nigérian'), ('GHS', 'Cedi ghanéen'), ('GNF', 'Franc guinéen'), ('CDF', 'Franc congolais')], default='EUR', max_length=3),
        ),
    ]
